dateModified: 1554889566
email:
  fromEmail: webdev@nixondesign.com
  fromName: Craft
  template: null
  transportType: craft\mail\transportadapters\Sendmail
  transportSettings: null
fieldGroups:
  059578ee-ad91-4430-b467-c870d8cf1579:
    name: Common
  fb69239b-76a5-43f2-b59f-0adffcac83e7:
    name: SEO
fields:
  9435729b-0cbb-4d4c-bc3d-1abd51e3892e:
    name: 'Alt text'
    handle: alt
    instructions: ''
    searchable: '0'
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 059578ee-ad91-4430-b467-c870d8cf1579
    contentColumnType: text
  7867a02a-c8b9-4136-8ffe-fcece191ca3c:
    name: Body
    handle: body
    instructions: ''
    searchable: '1'
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_body}}'
      localizeBlocks: false
    fieldGroup: 059578ee-ad91-4430-b467-c870d8cf1579
    contentColumnType: string
  8cfd9379-c00e-49e6-88c5-e5394a3eaf7c:
    name: 'Meta Title'
    handle: metaTitle
    instructions: ''
    searchable: '1'
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: fb69239b-76a5-43f2-b59f-0adffcac83e7
    contentColumnType: text
  eabfed67-715e-4222-9e32-9bd51ac22471:
    name: 'Meta Description'
    handle: metaDescription
    instructions: ''
    searchable: '1'
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: fb69239b-76a5-43f2-b59f-0adffcac83e7
    contentColumnType: text
matrixBlockTypes:
  b8cc71a5-3887-4789-a31a-c9b7b7960631:
    name: Text
    handle: text
    sortOrder: '2'
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      cb92abef-facf-4b86-8521-8ef1ffd73466:
        tabs:
          -
            name: Content
            sortOrder: '1'
            fields:
              e6a60e1a-23f0-4d30-b809-561e56330f27:
                required: '1'
                sortOrder: '1'
    fields:
      e6a60e1a-23f0-4d30-b809-561e56330f27:
        name: Text
        handle: text
        instructions: ''
        searchable: '1'
        translationMethod: none
        translationKeyFormat: null
        type: craft\redactor\Field
        settings:
          redactorConfig: Standard.json
          purifierConfig: ''
          cleanupHtml: '1'
          purifyHtml: '1'
          columnType: text
          availableVolumes: '*'
          availableTransforms: '*'
        fieldGroup: null
        contentColumnType: text
  aa2eaa16-dc8a-46f9-a82f-fc5d7a460eb8:
    name: Heading
    handle: heading
    sortOrder: '1'
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      1b052929-8c4b-4400-b778-4ee14a43782f:
        tabs:
          -
            name: Content
            sortOrder: '1'
            fields:
              761cac28-e032-467b-96ed-b3a0d1b17c2f:
                required: '1'
                sortOrder: '1'
              171d8286-303a-4222-8f11-664c1dd49891:
                required: '1'
                sortOrder: '2'
    fields:
      761cac28-e032-467b-96ed-b3a0d1b17c2f:
        name: Level
        handle: hx
        instructions: ''
        searchable: '1'
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\Dropdown
        settings:
          options:
            -
              label: One
              value: '1'
              default: '1'
            -
              label: Two
              value: '2'
              default: ''
            -
              label: Three
              value: '3'
              default: ''
        fieldGroup: null
        contentColumnType: string
      171d8286-303a-4222-8f11-664c1dd49891:
        name: Heading
        handle: heading
        instructions: ''
        searchable: '1'
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        fieldGroup: null
        contentColumnType: text
  bf649cdd-30ce-490d-aef0-493c9bb4651b:
    name: Blockquote
    handle: blockquote
    sortOrder: '3'
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      b00bc0a1-a48e-42d0-9638-f08dc9c9727a:
        tabs:
          -
            name: Content
            sortOrder: '1'
            fields:
              0e5225da-6c68-42ca-bde8-3a2247219969:
                required: '1'
                sortOrder: '1'
    fields:
      0e5225da-6c68-42ca-bde8-3a2247219969:
        name: Quote
        handle: quote
        instructions: ''
        searchable: '1'
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: '1'
          initialRows: '2'
          charLimit: ''
          columnType: text
        fieldGroup: null
        contentColumnType: text
  8b71776a-54bd-43e6-a5f1-9f6e2c5c516b:
    name: Image
    handle: image
    sortOrder: '4'
    field: 7867a02a-c8b9-4136-8ffe-fcece191ca3c
    fieldLayouts:
      d04d55c2-baff-4088-b0e7-a2f6f64e3c93:
        tabs:
          -
            name: Content
            sortOrder: '1'
            fields:
              7587301a-42cc-4897-a382-de451d6a474c:
                required: '1'
                sortOrder: '1'
    fields:
      7587301a-42cc-4897-a382-de451d6a474c:
        name: Image
        handle: image
        instructions: ''
        searchable: '1'
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Assets
        settings:
          useSingleFolder: ''
          defaultUploadLocationSource: 'volume:795e072f-98ce-4a14-ae63-4e3a4e5142ca'
          defaultUploadLocationSubpath: ''
          singleUploadLocationSource: 'volume:795e072f-98ce-4a14-ae63-4e3a4e5142ca'
          singleUploadLocationSubpath: ''
          restrictFiles: '1'
          allowedKinds:
            - image
          sources:
            - 'volume:9e21bfc8-59c7-4a1e-9695-b710f984ea53'
          source: null
          targetSiteId: null
          viewMode: large
          limit: '1'
          selectionLabel: 'Add an image'
          localizeRelations: false
        fieldGroup: null
        contentColumnType: string
plugins:
  assetrev:
    schemaVersion: 1.0.0
  cookies:
    schemaVersion: 1.0.0
  redactor:
    schemaVersion: 2.2.2
sections:
  de7026b1-fc54-49fa-93ab-9759b3c72110:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: false
    propagateEntries: true
    siteSettings:
      29077885-d696-4ee7-9a99-ea42e8f64311:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: index
    entryTypes:
      e11afaf6-11f4-4cb1-944a-ee397b8d8270:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  9dc3c5ac-0e8f-4d8e-a51c-a7ac78891c7f:
    name: 'Page Not Found'
    handle: pageNotFound
    type: single
    enableVersioning: false
    propagateEntries: true
    siteSettings:
      29077885-d696-4ee7-9a99-ea42e8f64311:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '404'
        template: '404'
    entryTypes:
      4a8d5656-d418-4987-99e9-5219c2d65824:
        name: 'Page Not Found'
        handle: pageNotFound
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
siteGroups:
  e70939fb-8b55-4880-b361-6437b2756120:
    name: Craft
sites:
  29077885-d696-4ee7-9a99-ea42e8f64311:
    siteGroup: e70939fb-8b55-4880-b361-6437b2756120
    name: Craft
    handle: default
    language: en-GB
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: Craft
  live: true
  schemaVersion: 3.1.26
  timeZone: Europe/London
volumes:
  9e21bfc8-59c7-4a1e-9695-b710f984ea53:
    name: Images
    handle: images
    type: craft\volumes\Local
    hasUrls: '1'
    url: '@web/uploads/images'
    settings:
      path: '@webroot/uploads/images'
    sortOrder: '2'
    fieldLayouts:
      00b9e43e-fb66-49f3-a719-d0e2bfe38334:
        tabs:
          -
            name: Content
            sortOrder: '1'
            fields:
              9435729b-0cbb-4d4c-bc3d-1abd51e3892e:
                required: '0'
                sortOrder: '1'
  795e072f-98ce-4a14-ae63-4e3a4e5142ca:
    name: Documents
    handle: documents
    type: craft\volumes\Local
    hasUrls: '1'
    url: '@web/uploads/documents'
    settings:
      path: '@webroot/uploads/documents'
    sortOrder: '1'
